SPEC = Gem::Specification.new do |spec| 
  spec.name = "bcms_pubcookie"
  spec.rubyforge_project = spec.name
  spec.version = "0.1.0"
  spec.summary = "A Pubcookie Module for BrowserCMS"
  spec.author = "James Hughes" 
  spec.email = "james@virtualjames.com" 
  spec.homepage = "http://www.virtualjames.com" 
  # spec.files += Dir["app/**/*"]
  # spec.files += Dir["db/migrate/*.rb"]
  # spec.files -= Dir["db/migrate/*_browsercms_*.rb"]
  # spec.files -= Dir["db/migrate/*_load_seed_data.rb"]
  spec.files += Dir["lib/bcms_pubcookie.rb"]
  spec.files += Dir["lib/bcms_pubcookie/*.rb"]
  spec.files += Dir["lib/pubcookie/*.rb"]
  spec.files += Dir["lib/pubcookie/**/*.rb"]
  spec.files += Dir["rails/init.rb"]
  spec.files += Dir["public/bcms/pubcookie/**/*"]
  spec.require_paths = ["lib"]
  spec.has_rdoc = false
  spec.extra_rdoc_files = ["README"]
  spec.add_dependency(%q<browsercms>, [">= 3.1.2"])
end
